### ISSUE TITLE
Apache2

### ISSUE THREAD

**Issue by iberno** [thedevdojo/larasail#1]
Hello Guys,

Using LARASAIL to install a Server on DO, the apache2 server is being installed.
I think that it's necessary change the install command php7.2 to:
apt-get install php7.2-cli php7.2-fpm. This way will install only php without Apache Server.

I make a mistake to create a website on different folder and when I look on my browser came on a Apache Server Message... It Works..

Thanks for now.

**Comment by tnylea** [comment]
Thanks man! I'll get that updated. Appreciate the feedback.

**Comment by wimurk** [comment]
Is this fixed?
