### ISSUE TITLE
Wondering about the security of storing root mysql password in /etc/.larasail/tmp/mysqlpass

### ISSUE THREAD

**Issue by hackerESQ** [thedevdojo/larasail#10]
Shouldn't there be a command that clears the password files stored in the /etc/.larasail/tmp/ directory? I'm concerned about the security of storing the passwords in plain text on the production server? I'm considering doing a PR to add that command.  Correct me if I'm wrong.

**Comment by bobbyiliev** [comment]
@hackerESQ indeed this is a good point. Maybe adding a step to clear the tmp folder and save the password at ~/.my.cnf (also chmod it to 600) would be a good step.

A PR would be appreciated!
