### ISSUE TITLE
Can Deployer do the same thing as larasail? 

### ISSUE THREAD

**Issue by LukaszJaro** [thedevdojo/larasail#103]
Just new to deploying Laravel apps, seems deployer is able to provision the server as well?

Also how does larasail handles updates to the server?

Thanks!

**Comment by bobbyiliev** [comment]
Hey!

You can update your server at any time with `apt update && apt upgrade`. Can you give a bit more information on what updates are you after exactly?

**Comment by bobbyiliev** [comment]
Yep, so you would just do `apt update && apt upgrade` on the server that will upgrade your OS and all packages like MySQL, Nginx, Redis and etc.

For installing a new PHP version you could just do:

```
PHP=8.2 # Or the version that you want to install
sudo apt-get install -y php$PHP-cli php$PHP-common php$PHP-mysql php$PHP-gd php$PHP-mysql php$PHP-curl php$PHP-mbstring php$PHP-xml php$PHP-zip php$PHP-fpm
```

And then update the Nginx server block PHP fpm definition: `fastcgi_pass unix:/run/php/php$phpVersionHere-fpm.sock;`.
