### ISSUE TITLE
Feature: Add support for SQLite

### ISSUE THREAD

**Issue by LukaszJaro** [thedevdojo/larasail#107]
I'm assuming there is no current support for SQLite? I'm planning to launch my app soon with SQLite, and it's actually one of the fastest growing Database in Laravel(according to state of Laravel 2024), even beating PostgreSQL.

Or alternatively, is it possible to use larasail without MySQL installation, then SQLite can be installed by some other means?

**Comment by bobbyiliev** [comment]
Hey!

SQLite is already installed: https://github.com/thedevdojo/larasail/blob/e0a4612f8fd467768363cf24fb9280b9b4028464/.larasail/setup#L134

So you can just stop mysql with:

```sh
sudo systemctl stop mysql
sudo systemctl disable mysql
```

And use SQLite as normal.
