### ISSUE TITLE
access mysql remotely on Windows 

### ISSUE THREAD

**Issue by VitaTamry** [thedevdojo/larasail#12]
This is a great time-saving package,
I just cannot access to MySQL on windows .. I followed your video tutorial but I don't have sequel Pro and I tried with workbench but it didn't work.

**Comment by bad33ndj3** [comment]
I also run into this on windows. Phpstorm does not connect.

**Comment by bobbyiliev** [comment]
I think that the best way to connect to MySQL from your local Windows machine would be to use any MySQL client which supports SSH tunneling.

That way you will connect to your MySQL service via SSH directly from your MySQL desktop client without the need of making any changes to the server itself.

Here is a really great tutorial on how to do that:

https://www.digitalocean.com/community/tutorials/how-to-connect-to-a-mysql-server-remotely-with-mysql-workbench
