### ISSUE TITLE
curl isn't working on a new droplet

### ISSUE THREAD

**Issue by Sourcefli** [thedevdojo/larasail#14]
I've tried installing 2 brand new droplets (to confirm I didn't make any errors the first time) as described on DevDojo.com, but once I enter the initial curl command and hit enter, it shows the larasail logo but stops after that and just shows a "$" prompt. Anything I enter here, even ls or any other basic commands return "command not found". I have to execute 'exit' to leave this mode.

Once I do hit exit, it brings me back to the initial (root@<ip address>:~#) prompt that I land on when initially logging in.

Note: if i try running the curl command a 2nd time, it does note that 'useradd: user 'larasail' already exists'

**Comment by pxgamer** [comment]
The `$` prompt appears when the user is switched to `larasail` with: https://github.com/thedevdojo/larasail/blob/d56865b3dee4aa35abd03e97787a1b7d458ed313/install#L62

The `larasail` user uses `/bin/sh` as its prompt by default, so the `/etc/bash.bashrc` aliases won't be registered. You can simply type `bash` at the `$` prompt if you want to use the aliases.

This can probably be resolved by adding `-s /bin/bash` to the `adduser` command:
https://github.com/thedevdojo/larasail/blob/d56865b3dee4aa35abd03e97787a1b7d458ed313/install#L21

-----

When going back to your usual user with `exit`, you can also `source /etc/bash.bashrc` which will register the `larasail` command:

![Example output of sourcing the bashrc](https://user-images.githubusercontent.com/1899334/65237441-950aa180-dad2-11e9-8716-b4610e2434de.png)

**Comment by Sourcefli** [comment]
Sweet, got it working. Thank you for your help

**Comment by Sourcefli** [comment]
Though, after further digging I saw out that PHP and composer were installed, but the laravel installer wasn't. 
I was able to add it pretty easily w/all the basics installed, but its worth noting for those who come across this thread
