### ISSUE TITLE
Remove PHP mcrypt as it is no longer needed

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/larasail#22]
Laravel does not need `mcrypt` extension anymore as `mcrypt` is obsolete

**Comment by TTiger** [comment]
First time contributing to Hacktoberfest - is the protocol to ask for a ticket before just taking it?

**Comment by bobbyiliev** [comment]
Hey @TTiger,

Yes, feel free to work on this one! Note that the PRs for Hacktoberfest count between 1 Oct and 31 Oct!

Good luck! 🙌

**Comment by thrix04** [comment]
Hello @TTiger ,
This is my first Hacktoberfest, can you please elaborate and also if possible assign this issue to me.

**Comment by thrix04** [comment]
hey @bobbyiliev , 
This is my first Hacktoberfest too. Can you please elaborate this to me and assign also if possible. 
Cheers.

**Comment by bobbyiliev** [comment]
Hi @thrix04, well it looks like that @TTiger already submitted a fix for this. Feel free to look into the other issues that are not yet being worked on 🙌
