### ISSUE TITLE
Can’t connect to MySQL using generates random password.

### ISSUE THREAD

**Issue by muhghazaliakbar** [thedevdojo/larasail#27]
Hi, I have installed this package and all working except the MySQL. I’m trying to login to database using command “mysql-u root -p” and enter the generated password from “larasail mysqlpass” but always denied. 

I think I have missed something but I don’t know what’s that. Anyone can help?

**Comment by bobbyiliev** [comment]
Hi there @muhghazaliakbar,

I have just tested this and it seems to be working as expected. 

What is the exact operating system that you are running this on? And did you run this on a fresh new droplet or did you have any other services preinstalled?

Also, make sure that you do not copy any whitespaces before and after the MySQL password.

**Comment by muhghazaliakbar** [comment]
Hey, @bobbyiliev I think I did something wrong with the MySQL stuff. Reinstalling the larasail and working as expected :)

**Comment by alexchirolde** [comment]
I'm having the same issue here with mysql, when installing throws this warning:

```
--------------------------------------------------
| Installing MySQL 
--------------------------------------------------
Hit:1 https://deb.nodesource.com/node_16.x jammy InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease                                                                 
Hit:3 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease                                                    
Hit:4 http://mirrors.digitalocean.com/ubuntu jammy InRelease                                           
Hit:5 http://mirrors.digitalocean.com/ubuntu jammy-updates InRelease             
Hit:6 http://mirrors.digitalocean.com/ubuntu jammy-backports InRelease           
Hit:7 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy InRelease         
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mysql-server is already the newest version (8.0.31-0ubuntu0.22.04.1).
The following packages were automatically installed and are no longer required:
  libflashrom1 libftdi1-2
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```
when I try to log in to mysql, using the credentials in the .env file or using mysql-u root -p it says access denied

**Comment by SamuelMwangiW** [comment]
Re-opening this issue while I investigate.

**Comment by SamuelMwangiW** [comment]
> --------------------------------------------------
> | Installing MySQL 
> --------------------------------------------------
> Hit:1 https://deb.nodesource.com/node_16.x jammy InRelease
> Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease                                                                 
> Hit:3 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease                                                    
> Hit:4 http://mirrors.digitalocean.com/ubuntu jammy InRelease                                           
> Hit:5 http://mirrors.digitalocean.com/ubuntu jammy-updates InRelease             
> Hit:6 http://mirrors.digitalocean.com/ubuntu jammy-backports InRelease           
> Hit:7 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy InRelease         
> Reading package lists... Done
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> mysql-server is already the newest version (8.0.31-0ubuntu0.22.04.1).

Hi @alexchirolde,

I have just tested this and it seems to be working as expected.

Looks to me like you had previously setup `mysql-server` on the host before attempting to setup `larasail` from the last line. If that's the case, kindly update `/home/larasail/.my.cnf` with the correct mysql username and password.

**Comment by alexchirolde** [comment]
I had to destroy the droplet and recreate everything again, I guess I did something wrong the first time, thxs @SamuelMwangiW
