### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by daledet** [thedevdojo/larasail#28]
I already have a laravel project built and ready to deploy. Will this help me with that? I followed all of the steps and have no idea what to do now.

**Comment by bobbyiliev** [comment]
Hi @daledet,

Yes this should help you quiet a bit, just follow the instructions and create a new project.

After that you can change the content of the project folder with your actual Laravel project and update your .env file to include the correct database credentials.

**Comment by daledet** [comment]
I thought of that, but can't figure out how to get my laravel project folders to the new project folders. Where is /var/www

**Comment by bobbyiliev** [comment]
What you could do is just use `cd` command to go to the `/var/www` directory:

```
cd /var/www
```

**Comment by daledet** [comment]
Well, yes, but how do I get the files from my laravel project into that directory. This makes no sense.

**Comment by daledet** [comment]
Now that I have gone down this path, there is no way out. I am totally screwed. Larasail was a huge mistake.

**Comment by bobbyiliev** [comment]
Getting files from your PC to your server is quite straight forward with git and GitHub. Just commit your files to GitHub, and then pull the files on your server. This is quite a standard workflow.
