### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by daledet** [thedevdojo/larasail#29]
I screwed up by opening a blank project with my actual domain name, and now when I start over it tells me the domain name already exists. Is it possible to delete the existing domain name and start over from scratch?
<img width="373" alt="Screenshot 2020-07-14 at 12 49 07 PM" src="https://user-images.githubusercontent.com/35194827/87417524-a0363d00-c5d0-11ea-9aa2-e23f260be1c7.png">

**Comment by bobbyiliev** [comment]
Hey there @daledet,

At the moment the script can only create new projects and not delete old ones. 

I could suggest two things in this case:

* Manually delete the project: you could do that by deleting the project from the /var/www/project_name folder and then deleting the Nginx server block from the `/etc/nginx/sites-enabled/project_name` and `/etc/nginx/sites-available/project_name` 

* If you do not have any other information on that Droplet, you could spin up a new one and run the script again
