### ISSUE TITLE
authentication failure

### ISSUE THREAD

**Issue by NathnC** [thedevdojo/larasail#3]
after following instructions, and trying su - larasail, using the password given via larasail pass it fails.

also when trying to connect to the mysqli server it errors, am i doing something wrong?

**Comment by tnylea** [comment]
Nope, that should be correct.

Are you using Digital Ocean and Ubuntu 16.04? Let me know and I'll do some testing this weekend.

**Comment by NathnC** [comment]
Yeah, brand new droplet on ubuntu 16.04.4 x64, it's super strange as I got excited for this - would make life a breeze

**Comment by bobbyiliev** [comment]
If you are already logged in as the larasail user there is no need to run the `su - larasail` command. 

To check the user that you are currently logged in as you can use the following command: 

```
whoami
```

If you are logged in as root then run the `su - larasail`.
