### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by daledet** [thedevdojo/larasail#31]
How do I uninstall Larasail from my machine?

**Comment by bobbyiliev** [comment]
Hey there @daledet,

To 'uninstall' LaraSail, you could just delete the `larasail` user from your system with the `userdel` command and then delete the `/etc/.larasail` folder with the `rm` command.

Note that LaraSail installs Nginx, MySQL, and PHP along as well, so if you no longer need the services, you can remove them with the `apt` command.

For more information on Linux server management I would recommend starting with this tutorial series here:

[https://www.digitalocean.com/community/tutorial_series/getting-started-with-linux](Getting Started with Linux)
