### ISSUE TITLE
Oh dear god, why?

### ISSUE THREAD

**Issue by daledet** [thedevdojo/larasail#32]
...can't software developers write readable instructions?
IMHO, every tech company should employ humanities scholars like me to write actual instructions for actual people. Please, image you didn't build it and don't know how it works, and start to explain it from that mindset.

**Comment by bobbyiliev** [comment]
Hey there,

I would recommend starting with this YouTube video on how to use this script:

https://www.youtube.com/watch?v=KHFOVDixnyw

Hope that this helps!
