### ISSUE TITLE
Add support for Laravel Jetstream

### ISSUE THREAD

**Issue by bobbyiliev** [thedevdojo/larasail#37]
Hi there,

With Laravel 8 out now, it will be nice to have an argument to install Laravel Jetstreamas well.

Hopefully, someone might be up for the challenge 🙌

**Comment by schmidfelix** [comment]
Hi,
I think I haven't understood your problem correctly, where do you wanna have this attribute?
You can simply add an `--jet` to `laravel new mywebsite`?

**Comment by bobbyiliev** [comment]
Hi @schmidfelix,

Ah yes indeed you are right, seems like that the script did not need any updates after the Laravel 8 release and seems to be working as expected.
