### ISSUE TITLE
Bug: `laravel` is not available in $PATH on Ubuntu 20.04 (LTS) x64

### ISSUE THREAD

**Issue by lexuzieel** [thedevdojo/larasail#39]
### Describe the bug

After installing larasail and running `larasail setup` I tried executing the next step:
```
cd /var/www && laravel new mywebsite
```
which in turn printed:
```
laravel: command not found
```

### To Reproduce

1. Create Ubuntu 20.04 (LTS) x64 droplet on Digital Ocean
2. Install larasail
3. Try executing `laravel` under `larasail` user

### Expected behavior

Global command `larasail` works

### Screenshots

![](https://i.imgur.com/xwvRhL1.png)

### Context

Checking $PATH variable I found that `/home/larasail/.composer/vendor/bin` is actually present, however the directory itself is missing.

### Proposed solution

Use `composer create-project --prefer-dist laravel/laravel <project-name>` instead ([reference](https://laravel.com/docs/8.x/installation#installing-laravel))

**Comment by bobbyiliev** [comment]
Hi there @lexuzieel 

I was able to replicate the problem. Seems like that the Laravel installer is stored at `~/.config/composer/vendor/laravel/installer/bin/laravel` now.

To fix that you can add the following line in your `~/.bashrc` file:

```
export PATH=.config/composer/vendor/bin/:$PATH
```

And then run:

```
source ~/.bashrc
```

I will submit a PR with a fix soon!
