### ISSUE TITLE
Support for Ubuntu 18.04?

### ISSUE THREAD

**Issue by shirshak55** [thedevdojo/larasail#4]
There is weird problem with ubuntu 18.04 after larasail setup . It works well in ubuntu 16.04 but i guess many people will use 18.04 

Thanks :)

**Comment by tnylea** [comment]
Howdy,

What's the weird problem you are having, can you share a screenshot or a code snippet of the error. Let me know :) I would love to get this working on the latest version of Ubuntu as well.

Thanks.

**Comment by bloggervista** [comment]
@tnylea 
Here is screenshot
<img width="1680" alt="screen shot 2018-06-14 at 11 45 20 pm" src="https://user-images.githubusercontent.com/8097377/41429539-151ed5d8-702d-11e8-9191-ad6ed4ddbdf6.png">

**Comment by monirulpathan** [comment]
I just typed in for Ubuntu 18, I just typed in
bash
And it was fine from there on.

**Comment by ThantZinWin** [comment]
You continue command this. 
sudo su root

Thank:)

**Comment by sarperkaya** [comment]
#18

**Comment by shirshak55** [comment]
i am closing this issue. I realized the shell was changed to /bin/sh so i don't think it is issue for many people.
