### ISSUE TITLE
Feature: Option to ignore www.$domain

### ISSUE THREAD

**Issue by SamuelMwangiW** [thedevdojo/larasail#57]
### Is your feature request related to a problem? Please describe.
There are circumstances when the www.$domain is not necessary especially for subdomains e.g app.example.com. For such instances, it'd be amazing to have the option to setup nginx host and Letsencrypt only for the subdomain without necessary needing to add www.app.example.com CNAME. Not doing so, certbot fails during setup

### Describe the solution you'd like
If sounds reasonable, am willing to work on a PR that adds an optional parameter whether to add the www.$domain in .larasail/host.

### Describe alternatives you've considered
Always adding a www CNAME while setting up even when it's totally unnecessary.

### Additional context
I hope the above is sufficient

**Comment by bobbyiliev** [comment]
Hi there @SamuelMwangiW 👋

Yes, very good point! I've noticed this problem the other day too.

A PR will be highly appreciated!

Regards,
Bobby

**Comment by SamuelMwangiW** [comment]
@bobbyiliev thanks for the nice words. I will try get a PR ready for review soon. This repo has saved me substantial man-hours.
