### ISSUE TITLE
Feature: install different version of mysql

### ISSUE THREAD

**Issue by jrrmcalcio** [thedevdojo/larasail#59]
Thank you for this great tool.  A question. Is it possible to install a different version of mysql? Just like php?

**Comment by bobbyiliev** [comment]
Hi there!

Good suggestion. It should be possible to update the script and allow an option for the latest MySQL 5.x and latest 8.x.

I will look into it!

**Comment by bobbyiliev** [comment]
Thanks to @SamuelMwangiW we can now choose between MariaDB and MySQL. Do you think that this covers your request @jrrmcalcio? Or would you prefer to be able to choose a specific MySQL version too?

**Comment by bobbyiliev** [comment]
Closing this issue as the script now gives you the choice between MariaDB and MySQL thanks to @SamuelMwangiW 🚀
