### ISSUE TITLE
Help: All steps are done but when I visit the IP Public I got Nginx page?

### ISSUE THREAD

**Issue by RabieAli95** [thedevdojo/larasail#74]
I follow all steps but when I visit the IP Public I got the Nginx page?

**Comment by SamuelMwangiW** [comment]
Hi @RabieAli95. Kindly elaborate which steps you followed. Did you add a site and how did you add it?

**Comment by RabieAli95** [comment]
@SamuelMwangiW  

https://www.youtube.com/watch?v=KHFOVDixnyw&t=436s

**Comment by SamuelMwangiW** [comment]
By visiting the public IP, you definitely will get nginx default site. You need to add a site which you do by following the steps in the Creating a New Site [section of the readme](https://github.com/thedevdojo/larasail#creating-a-new-site). 

You will note that in the Video, Tony does this by running `larasail host mywebsite.com /var/www/mywebsite` and then adding an entry in `/etc/hosts` to resolve `mywebsite.com` to the Digital Ocean droplet.

If you intend to replace the default site with your preferred Laravel site, you may update the default nginx config in `/etc/nginx` directory

**Comment by RabieAli95** [comment]
@SamuelMwangiW 

I did as Tony did but I put my domain instead of `mywebsite.com`  then when I went to `sites-availables` in Nginx, I got two, the default and the domain that I put!

**Comment by SamuelMwangiW** [comment]
Then you should be able to access the site laravel with the FQDN

**Comment by RabieAli95** [comment]
@SamuelMwangiW That is why I've asked! everything is correct but the main IP shows me the Nginx page instead of the Laravel project!

**Comment by SamuelMwangiW** [comment]
Kindly see my [answers earlier](https://github.com/thedevdojo/larasail/issues/74#issuecomment-920261652) to see the laravel site, you need to access using the FQDN. If you visit the public ip then you'll see the default nginx site.
