### ISSUE TITLE
What about SSL certificate integration?

### ISSUE THREAD

**Issue by napalias** [thedevdojo/larasail#8]
Hey Tony, what about SSL integration? Can you tray add https://certbot.eff.org/ ?

**Comment by napalias** [comment]
Your script not yet, but i had added to my bookmark for when i boot next server. 
Byt certbot i use often :)

**Comment by milanchheda** [comment]
I have used larasail and it's smooth as breeze. Made it so easy to setup a laravel application. But I would agree with @napalias, having an SSL integration would be awesome. A command to install certbot for domains for sub-domains.

**Comment by wimurk** [comment]
+1

**Comment by bobbyiliev** [comment]
Just submitted a PR for this functionality:

https://github.com/thedevdojo/larasail/pull/17

**Comment by wimurk** [comment]
@bobbyiliev the project is dead for 2 years. I don't think this is maintained anymore

**Comment by bobbyiliev** [comment]
#17 Merged a fix which includes Let's Encrypt installation option
