### ISSUE TITLE
Discussion: Set php 8.0 as the Default

### ISSUE THREAD

**Issue by SamuelMwangiW** [thedevdojo/larasail#83]
### Is your feature request related to a problem? Please describe.

Am opening a discussion here on whether it makes sense to set php 8.0 as the default in time for [Laravel 9's release](https://laravel.com/docs/8.x/releases) scheduled for January 25th, 2022. Related to this, might want to opinions on whether Larasail should continue supporting 7.1 and 7.2 beyond 2022

### Describe the solution you'd like

Tag a release with 7.4 as the default, add setup instructions in the README and switch to 8.0 from the new year going forward.

### Describe alternatives you've considered

Status quo

### Additional context

Following the release of PHP 8.1, version 7.3 will be going immediately out of life.
Version 7.4 on the other hand will cease active development and shall only receive security patches for the next few months.
Symphony 6 which came out last month has a minimum requirement of php8.0 and Laravel 9 which shall be coming out next month will also require >=8.0.

**Comment by bobbyiliev** [comment]
Thanks for bringing this up Samuel!

I think that this is a very good idea, I think that we should go for PHP 8.0 as the active support for 7.4 has ended last week.

![PHP 7.4 end of active support](https://user-images.githubusercontent.com/21223421/144711678-63c8fa00-7694-4a86-8431-1ef23377fea5.png)

If needed, people would still be able to specify 7.4 in case that they need it for a specific project, but I think it is good to encourage everyone to go with 8.x.

**Comment by SamuelMwangiW** [comment]
Thanks Bobby for your input. I Will pr a switch to php8.0 as the default. I will await to see the community feedback on php versions 7.1 and 7.2
