### ISSUE TITLE
www. alias is not setup

### ISSUE THREAD

**Issue by sutcliffe121** [thedevdojo/larasail#85]
### Describe the bug

How can I verify that '--www-alias' has worked?

The www. domain to my site doesn't appear to work. I added '--www-alias' when running larasail host.

No SSL is setup for the www. domain and it displays the nginx page when accessed (rather than my site).
 
https://testing.cjs-web.co.uk - works
http://www.test.cjs-web.co.uk - displays nginx page

I setup a CNAME record as follows:
![image](https://user-images.githubusercontent.com/33236577/147546384-8bb3f418-a416-4664-a3c9-ca9ad4190cbb.png)

I have a Laravel site in a Bitbucket repo, using Larasail to setup a Digital Ocean droplet.

### To Reproduce

The commands I ran on my droplet:

curl -sL https://github.com/thedevdojo/larasail/archive/master.tar.gz | tar xz && source larasail-master/install

larasail setup php74

cd /var/www && git clone https://myusername@bitbucket.org/myusername/myrepo.git

composer install
cp .env.example .env
php artisan key:generate

larasail host testing.cjs-web.co.uk /var/www/cjsweb --www-alias

**Comment by SamuelMwangiW** [comment]
Thanks @sutcliffe121 for reporting the issue. Should be fixed by #86

**Comment by sutcliffe121** [comment]
Thanks @SamuelMwangiW, I can confirm the issue is now fixed and working as expected.
