### ISSUE TITLE
Help: certbot auto renew SSL certs?

### ISSUE THREAD

**Issue by sutcliffe121** [thedevdojo/larasail#87]
Does Larasail setup certbot to auto renew SSL certifications?

If not, what is the best way to set this up? I have read different methods.

https://eff-certbot.readthedocs.io/en/stable/using.html#setting-up-automated-renewal says to run:

`SLEEPTIME=$(awk 'BEGIN{srand(); print int(rand()*(3600+1))}'); echo "0 0,12 * * * root sleep $SLEEPTIME && certbot renew -q" | sudo tee -a /etc/crontab > /dev/null`

https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/ says:

`$ crontab -e`  and add
0 12 * * * /usr/bin/certbot renew --quiet

Thanks in advance,

**Comment by SamuelMwangiW** [comment]
Hi @sutcliffe121, Yes Larasail adds a certificates auto renewal during `larasail setup` in this line below: 
https://github.com/thedevdojo/larasail/blob/ced7fede2a46f74fc291df5d8566f2d2ff33d5f4/.larasail/setup#L178

For most setups, this should be able to renew and keep your ssl certificate renewed

**Comment by sutcliffe121** [comment]
Okay great. I can see the entry in /etc/crontab on my droplet. 

Thanks for your help.
