### ISSUE TITLE
How to remove a site or move site folder

### ISSUE THREAD

**Issue by emredipi** [thedevdojo/larasail#9]
I accidentally created my website in the wrong path. I need to change it. In the larasail command list I could not find "remove" or "replace".

**Comment by emredipi** [comment]
Also, can you please add a settings tool. For example, in forge there is php file upload size setting. In digital ocean with your script I can serve my sites but configuring the server is very difficult. Especially, I could not fix the file size problem for 3 days.

**Comment by wimurk** [comment]
Larasail only installs the necessary commands. what you are looking for is your OS commands. 
check out nginx https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-server-blocks-virtual-hosts-on-ubuntu-16-04
