### ISSUE TITLE
Feature: Update Php Version

### ISSUE THREAD

**Issue by 221910938** [thedevdojo/larasail#94]
# Update Php Version

For laravel 9 and newer versions you need php version 8.1 or newer, otherwise it is often incompatible and can cause errors when deploying.

**Comment by SamuelMwangiW** [comment]
@221910938 To quote the [readme](https://github.com/thedevdojo/larasail/blob/master/README.md#setup-your-server)

> The default configuration will install Nginx, PHP 8.0, and MySQL 8. If you wish to use PHP 7.1, 7.2, 7.3, 7.4 or 8.1 you can include the argument php71/php72/php73/php74/php81 like so:
> >larasail setup php71 # Install with PHP 7.1
> >larasail setup php72 # Install with PHP 7.2
> >larasail setup php73 # Install with PHP 7.3
> >larasail setup php74 # Install with PHP 7.4
> >larasail setup php81 # Install with PHP 8.1

The minimum supported version for Laravel 9 is [8.0.2](https://github.com/laravel/laravel/blob/52b741c79b6a8a4a6b900231203561f48af35b1c/composer.json#L8). I understand that Laravel 10 will require php 8.1 as a minimum however it'll not be released until Feb 2023.

You are welcome to send a PR if you believe this is incorrect
